mycooltv:
  predis:
    url: http://192.168.20.123:40001/predis/jobs
mf:
  assert: true

spring:
  application:
    name: demo
  profiles:
    active: test
logging:
  level:
    root: info    # debug:可以看到一些 debug 日志
debug: false       # 纯粹为了debug initializeEarlyLoggingLevel方法的日志